parameters:
     security.authentication.success_handler.class: PFA\EnsaoboxBundle\Handler\LoginSuccessHandler

services:
    security.authentication.customized_success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments:  [@router, @security.context]