<?php

namespace PFA\EnsaoboxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilieresRepository extends EntityRepository
{
}
