pfa_ensaobox_homepage:
    path:     /
    defaults: { _controller: PFAEnsaoboxBundle:Dashboard:index }

pfa_ensaobox_ajouter_files:
    path:    /prof/document/addFiles
    defaults: { _controller: PFAEnsaoboxBundle:Upload:ajouter}

pfa_ensaobox_afficher_files:
    path:    /document/showFiles
    defaults: { _controller: PFAEnsaoboxBundle:ShowFiles:ajouter}

pfa_ensaobox_admin:
    path:     /admin/createusers
    defaults: { _controller: PFAEnsaoboxBundle:Admin:createUsers }



